### PR TITLE
Add project status to README: currently experimental and not supported

### PR DESCRIPTION
**Pull request by pongad**

### CODE REVIEW

**Comment by saicheems** [comment]
Lgtm, incidentally: that's why coverage has been so poor!! I knew was missing a few lines but not that many... any way to tell codecov to ignore the readme?

**Comment by saicheems** [comment]
No, wait that's not it, nvm. Weird that it says coverage decreases

**Comment by pongad** [comment]
@saicheems I have no clue what codecov is doing. I should probably read up on it. Are you still OK with merging this?

**Comment by saicheems** [comment]
Yup

**Pull request merged**
