### PR TITLE
Remove obsolete client options and dial code

### PR DESCRIPTION
**Pull request by saicheems**

### CODE REVIEW

**Comment by pongad** [comment]
Deleted code! LGTM

**Comment by jba** [comment]
LGTM.

**Comment by saicheems** [comment]
Note for the future:

This can't be merged until gcloud is updated with a newer client - master will break if we merge this change before then.

**Comment by jba** [comment]
What needs to be done, or who needs to be contacted, to update gcloud?

**Comment by saicheems** [comment]
Well, presumably you :)

@pongad Can you make a PR with the latest generator against gcloud master? I think David Day, Michael McGreevy, and jba are the right reviewers.

**Comment by jba** [comment]
Oh, you don't mean the gcloud tool, you mean the gcloud-golang repo.
Nothing in that repo currently depends on that code, you I think you can
submit your PR.

**Comment by saicheems** [comment]
Ah, what I meant was the `apiv2

**Comment by saicheems** [comment]
So this can be merged on September 12th

**Comment by pongad** [comment]
Superseded by https://github.com/googleapis/gax-go/commit/ed6ab759ab548d1e6e070f53f9d1105d2d8128b0

**Pull request closed without merging**
